services:
  fontawesome:
    container_name: fontawesome
    build: .
    env_file:
      - .env
    volumes:
      - ./fontawesome:/usr/share/nginx/html/fontawesome:ro
    networks:
      - container-dmz
    environment:
      - NGINX_HOST=${APP_URL}
      - NGINX_PORT=80
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.fontawesome.rule: Host(`${APP_URL}`)
      traefik.http.routers.fontawesome.entrypoints: websecure
      traefik.http.routers.fontawesome.tls.certresolver: letsencrypt
      traefik.http.routers.fontawesome.middlewares: internal_only@file
      traefik.http.services.fontawesome.loadbalancer.server.port: 80

networks:
  container-dmz:
    external: true
